### ISSUE TITLE
bang, itu foto profile kamu dari anime apa?

### ISSUE THREAD

**Issue by ingrurat** [adityaHardi17/adityahardi17#1]

**Comment by adityahardi** [comment]
yang mana bang

**Comment by ingrurat** [comment]
> yang mana bang

udah kamu ganti bang foto profilnya

**Comment by adityahardi** [comment]
![wp11312154-vestia-zeta-wallpapers-crop](https://github.com/user-attachments/assets/798529bc-1ee4-4caa-9f1b-1014ff1fa346)

itu bang?, bukan anim bg itu vtuber (vestia zeta)

**Comment by ingrurat** [comment]
thx bang
